CREATE DATABASE employees;

CREATE TABLE IF NOT EXISTS Employees
(
    id      INTEGER NOT NULL AUTO_INCREMENT,
    name     VARCHAR(128) NOT NULL,
    position VARCHAR(128) NOT NULL,
    phone    VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);
